@url = http://localhost:8000

### Get Request
GET {{url}}/user


### Post Request
POST {{url}}/api/v1/auth/register
Content-Type: application/json

{
    "fName":"Gyanendra",
    "lName":"Poudel",
    "email":"ga9@gmail.com",
    "password":"1234"

}

### Post Request to activate new user
POST {{url}}/api/v1/auth/activate-user
Content-Type: application/json

{
    "sessionId":"677a475952bbe79326d76821",
    "t":"50ce8a86-d99f-4b25-bbef-e8fb7c42132f"
}