@url = http://localhost:8000

### Get Request
GET {{url}}/user


### Post Request
POST {{url}}/api/v1/auth/register
Content-Type: application/json

{
    "fName":"Gyanendra",
    "lName":"Poudel",
    "email":"ga9@gmail.com",
    "password":"1234"

}

### Post Request to activate new user
POST {{url}}/api/v1/auth/activate-user
Content-Type: application/json

{
    "sessionId":"677b348a8690e8a4c5cbc00a",
    "t":"fb297dd7-98b3-43ce-bc71-3fcdb4a42f64"
}