@url = http://localhost:8000

### Get Request
GET {{url}}/user


### Post Request
POST {{url}}/api/v1/auth/register
Content-Type: application/json

{
    "fName":"Gyanendra",
    "lName":"Poudel",
    "email":"g10@gmail.com",
    "password":"1234"

}

### Post Request to activate new user
POST {{url}}/api/v1/auth/activate-user
Content-Type: application/json

{
    "sessionId":"677b3e66d10826f8cddb502f",
    "t":"eb1a6a82-7290-4c2f-82bf-166fcb9447e8"
}